def grind19(number : int = 1):
	import random

	sdvx19 = {"A Lasting Promise",
	"Absolute Domination",	
	"Awakening",	
	"BELOBOG",	
	"Chrono Diver -PENDULUMs-",	
	"Deadly force",	
	"Dyscontrolled Galaxy",	
	"Elemental Creation",	
	"Failnaught",	
	"Fin.ArcDeaR",	
	"Fly Like You",	
	"FREEDOM DiVE",	
	"GERBERA -For Finalists-",	
	"KAC 2013 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- Empress Side MXM",	
	"Last Resort",	
	"Sailing Force",	
	"Staring at star",	
	"TWO-TORIAL",	
	"Xéroa",	
	"セイレーン ～悲壮の竪琴～",
	"逆月",	
	"KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Empress Side EXH",
	"FLOWER",	
	"Garakuta Doll Play",	
	"Got more raves？",	
	"きたさいたま2000",	
	"極圏",	
	"ΑΩ",	
	"Blastix Riotz",	
	"DIABLOSIS::Nāga",	
	"Everlasting Message",	
	"FLügeL《Λrp:ΣggyØ》",	
	"KAC 2012 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX-",
	"KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Emperor Side GRV",	
	"Lord=Crossight",	
	"Preserved Valkyria",	
	"XyHATTE",
	"月光乱舞",	
	"Firestorm",	
	"HAVOX",
	"KAC 2013 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- Emperor Side EXH",
	"veRtrageS",
	"XHAOS JUDGE",	
	"Booths of Fighters",	
	"For UltraPlayers HVN",	
	"INSECTICIDE",	
	"Quietus Ray",	
	"Verse IV",	
	"バンブーソード・ガール",	
	"Bangin' Burst GRV",	
	"Black Emperor",	
	"BLACK or WHITE?",	
	"Growth Memories",	
	"snow storm -euphoria-",	
	"XROSS INFECTION",	
	"Bangin' Burst EXH",	
	"For UltraPlayers EXH",	
	"大宇宙ステージ",	
	"Ganymede kamome mix",	
	"Max Burning!!"}

	draw = random.sample(sdvx19,number)
	return draw