import random

def grind19():
  sdvx19 = [
    "A Lasting Promise",
    "Absolute Domination",  
    "Awakening",  
    "BELOBOG",  
    "Chrono Diver -PENDULUMs-", 
    "Deadly force", 
    "Dyscontrolled Galaxy", 
    "Elemental Creation", 
    "Failnaught", 
    "Fin.ArcDeaR",  
    "Fly Like You", 
    "FREEDOM DiVE", 
    "GERBERA -For Finalists-",  
    "KAC 2013 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- Empress Side",  
    "Last Resort",  
    "Sailing Force",  
    "Staring at star",  
    "TWO-TORIAL", 
    "Xéroa",  
    "セイレーン ～悲壮の竪琴～",
    "逆月", 
    "FLOWER", 
    "Garakuta Doll Play IS A 19 AND YOU CAN'T TAKE IT AWAY FROM ME JOHN KONAMI",  
    "Got more raves？",  
    "きたさいたま2000", 
    "極圏", 
    "ΑΩ", 
    "Blastix Riotz",  
    "DIABLOSIS::Nāga",  
    "Everlasting Message",  
    "FLügeL《Λrp:ΣggyØ》",  
    "KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Emperor Side",  
    "Lord=Crossight", 
    "Preserved Valkyria", 
    "XyHATTE",
    "月光乱舞", 
    "Booths of Fighters", 
    "For UltraPlayers", 
    "INSECTICIDE",  
    "Quietus Ray",  
    "Verse IV", 
    "バンブーソード・ガール",  
    "Bangin' Burst",  
    "Black Emperor",  
    "BLACK or WHITE?",  
    "Growth Memories",  
    "snow storm -euphoria-",  
    "XROSS INFECTION",  
    "大宇宙ステージ",  
    "Ganymede kamome mix",  
    "Innocent Tempest",
    "ラクガキスト",
    "音楽 -resolve-",
    "Ghost Family Living In Graveyard",
    "Lancelot ~Flame of the Rebellion",
    "TENKAICHI ULTIMATE BOSSRUSH MEDLEY",
    "THE凸GENERATOR"
  ]

  draw = random.choice(sdvx19)
  return draw